services:
  - type: web
    name: anitok-api
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: anitok-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: anitok-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: anitok-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: anitok-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: anitok-db
          property: password
